/**
 * MEGA POOL 11.0 - THE ULTIMATE ENCYCLOPEDIA
 * 20 Categorie - Target: Scientifico / Universitario / Expert
 * 10 domande esatte per ogni livello di punteggio per categoria (50 domande a categoria).
 */
const CATEGORIES_POOL = [
    {
        id: "phys_chem",
        title: "Fisica & Chimica",
        questions: [
            // 100
            { q: "Qual è il valore medio dell'accelerazione di gravità (g) sulla Terra?", a: "9.81 m/s²", p: 100 },
            { q: "Qual è il simbolo chimico del Potassio?", a: "K", p: 100 },
            { q: "Qual è la formula chimica dell'acqua?", a: "H2O", p: 100 },
            { q: "Qual è il gas nobile più leggero della tavola periodica?", a: "Elio", p: 100 },
            { q: "Qual è il simbolo chimico dell'Oro?", a: "Au", p: 100 },
            { q: "Come si chiama il passaggio di stato diretto da Solido a Gas?", a: "Sublimazione", p: 100 },
            { q: "Qual è il simbolo chimico dell'Ossigeno?", a: "O", p: 100 },
            { q: "Quale tipo di carica elettrica possiede un protone?", a: "Carica positiva", p: 100 },
            { q: "Nel Sistema Internazionale, il Newton è l'unità di misura di quale grandezza?", a: "Forza", p: 100 },
            { q: "Qual è il simbolo chimico del Carbonio?", a: "C", p: 100 },
            // 200
            { q: "Qual è il simbolo chimico dell'Argento?", a: "Ag", p: 200 },
            { q: "Qual è l'unità di misura della frequenza nel Sistema Internazionale?", a: "Hertz", p: 200 },
            { q: "Quale composto chimico corrisponde alla formula HCl?", a: "Acido Cloridrico", p: 200 },
            { q: "Quale celebre legge dell'elettrotecnica è espressa dalla formula V = R * I?", a: "Prima Legge di Ohm", p: 200 },
            { q: "Quale principio fisico regola il galleggiamento dei corpi nei fluidi?", a: "Principio di Archimede", p: 200 },
            { q: "Qual è il simbolo chimico del Ferro?", a: "Fe", p: 200 },
            { q: "Qual è il simbolo chimico del Rame?", a: "Cu", p: 200 },
            { q: "Il Joule è l'unità di misura di energia, calore e di quale altra grandezza?", a: "Lavoro", p: 200 },
            { q: "Quale sostanza chimica comune è composta da NaCl?", a: "Cloruro di Sodio (Sale da cucina)", p: 200 },
            { q: "Qual è il simbolo chimico dell'Azoto?", a: "N", p: 200 },
            // 300
            { q: "Quale idrocarburo aromatico ha formula chimica C6H6?", a: "Benzene", p: 300 },
            { q: "Quale fisico britannico scoprì l'elettrone nel 1897 usando i raggi catodici?", a: "J.J. Thomson", p: 300 },
            { q: "Quale forte acido minerale corrisponde alla formula H2SO4?", a: "Acido Solforico", p: 300 },
            { q: "Quale particella subatomica è priva di carica elettrica?", a: "Neutrone", p: 300 },
            { q: "Quale fisico danese propose un modello atomico con orbite quantizzate nel 1913?", a: "Niels Bohr", p: 300 },
            { q: "A quanti chilometri al secondo corrisponde, approssimativamente, la velocità della luce?", a: "300.000 km/s", p: 300 },
            { q: "Quale idrocarburo alcano corrisponde alla formula CH4?", a: "Metano", p: 300 },
            { q: "Nel Sistema Internazionale, il Coulomb misura quale grandezza?", a: "Carica elettrica", p: 300 },
            { q: "Come è chiamato il passaggio di stato da Gas a Liquido?", a: "Condensazione", p: 300 },
            { q: "Qual è il simbolo chimico del Piombo?", a: "Pb", p: 300 },
            // 400
            { q: "Qual è il valore approssimato della Costante di Planck (h) in J·s?", a: "6.626 × 10^-34", p: 400 },
            { q: "Quale teoria rivoluzionaria pubblicò Albert Einstein nel 1915?", a: "Relatività Generale", p: 400 },
            { q: "Come si chiama una trasformazione termodinamica che avviene a volume costante?", a: "Isocora", p: 400 },
            { q: "Quale principio stabilisce che due fermioni non possono avere gli stessi numeri quantici?", a: "Principio di esclusione di Pauli", p: 400 },
            { q: "Quale acido è rappresentato dalla formula chimica HNO3?", a: "Acido Nitrico", p: 400 },
            { q: "Quale scienziato vinse il Nobel per aver scoperto il neutrone nel 1932?", a: "James Chadwick", p: 400 },
            { q: "Qual è il numero atomico (Z) dell'Uranio?", a: "92", p: 400 },
            { q: "Qual è il volume occupato da una mole di gas ideale in condizioni STP?", a: "22.414 Litri", p: 400 },
            { q: "Quale scienziata isolò per la prima volta elementi come Polonio e Radio?", a: "Marie Curie", p: 400 },
            { q: "Come è chiamata una trasformazione termodinamica che avviene a pressione costante?", a: "Isobara", p: 400 },
            // 500
            { q: "Qual è il valore esatto della velocità della luce nel vuoto espresso in m/s?", a: "299.792.458 m/s", p: 500 },
            { q: "Quale scienziato scozzese ha unificato l'elettromagnetismo con le sue 4 equazioni?", a: "James Clerk Maxwell", p: 500 },
            { q: "Quale grandezza termodinamica misura il grado di disordine di un sistema?", a: "Entropia", p: 500 },
            { q: "Come si definisce una trasformazione termodinamica senza scambio di calore con l'esterno?", a: "Adiabatica", p: 500 },
            { q: "Quale bosone, confermato nel 2012, conferisce la massa alle particelle fondamentali?", a: "Bosone di Higgs", p: 500 },
            { q: "Qual è il valore approssimato della Costante di Gravitazione Universale (G)?", a: "6.67 × 10^-11 N(m/kg)²", p: 500 },
            { q: "Quale effetto descrive il cambiamento di frequenza di un'onda causato dal moto della sorgente?", a: "Effetto Doppler", p: 500 },
            { q: "Quale fenomeno fisico, spiegato da Einstein nel 1905, gli valse il Premio Nobel?", a: "Effetto fotoelettrico", p: 500 },
            { q: "Quale isotopo dell'idrogeno possiede un protone e un neutrone nel nucleo?", a: "Deuterio", p: 500 },
            { q: "Quale legge della fluidostatica descrive la pressione esercitata da una colonna di fluido?", a: "Legge di Stevino", p: 500 }
        ]
    },
    {
        id: "hist_ancient",
        title: "Storia Antica/Med.",
        questions: [
            // 100
            { q: "Chi fu storicamente il primo Imperatore di Roma?", a: "Augusto (Ottaviano)", p: 100 },
            { q: "Cosa accadde storicamente alle Idi di Marzo del 44 a.C.?", a: "L'assassinio di Giulio Cesare", p: 100 },
            { q: "Quale città nordafricana fu la principale nemica di Roma nelle Guerre Puniche?", a: "Cartagine", p: 100 },
            { q: "Quale città greca antica era celebre per la sua rigida educazione militare?", a: "Sparta", p: 100 },
            { q: "Quale re di Macedonia creò uno dei più vasti imperi dell'antichità fino all'India?", a: "Alessandro Magno", p: 100 },
            { q: "Quale fiume attraversò Giulio Cesare pronunciando 'Alea iacta est'?", a: "Rubicone", p: 100 },
            { q: "Quale città romana fu sepolta dall'eruzione del Vesuvio nel 79 d.C.?", a: "Pompei", p: 100 },
            { q: "Secondo la leggenda, chi fu il fondatore e primo re di Roma nel 753 a.C.?", a: "Romolo", p: 100 },
            { q: "Come fu ribattezzata la città di Bisanzio nel 330 d.C. dall'imperatore Costantino?", a: "Costantinopoli", p: 100 },
            { q: "Quali imponenti strutture venivano erette come tombe monumentali per i Faraoni egizi?", a: "Piramidi", p: 100 },
            // 200
            { q: "In quale anno Cristoforo Colombo arrivò nelle Americhe?", a: "1492", p: 200 },
            { q: "Chi uscì vittorioso dalla battaglia navale di Azio nel 31 a.C.?", a: "Ottaviano (Augusto)", p: 200 },
            { q: "Quale generale cartaginese valicò le Alpi usando gli elefanti?", a: "Annibale", p: 200 },
            { q: "Quale imperatore divise definitivamente l'Impero Romano alla sua morte nel 395 d.C.?", a: "Teodosio I", p: 200 },
            { q: "In quale anno si fissa convenzionalmente la caduta dell'Impero Romano d'Occidente?", a: "476 d.C.", p: 200 },
            { q: "Quale famosa battaglia tra Greci e Persiani fu combattuta nel 490 a.C.?", a: "Battaglia di Maratona", p: 200 },
            { q: "Quale comandante trionfò contro i Romani nella devastante Battaglia di Canne?", a: "Annibale", p: 200 },
            { q: "Quale navigatore genovese viaggiò per la Spagna cercando una rotta ovest per le Indie?", a: "Cristoforo Colombo", p: 200 },
            { q: "Come si chiama la lunga guerra che contrappose Sparta e Atene nel V secolo a.C.?", a: "Guerra del Peloponneso", p: 200 },
            { q: "Quale fortificazione in pietra fu costruita dai Romani per tagliare in due la Britannia?", a: "Vallo di Adriano", p: 200 },
            // 300
            { q: "Quale imperatore romano istituì il sistema di governo noto come Tetrarchia?", a: "Diocleziano", p: 300 },
            { q: "In quale celebre assedio Giulio Cesare sconfisse definitivamente Vercingetorige?", a: "Assedio di Alesia", p: 300 },
            { q: "Chi fu incoronato Imperatore del Sacro Romano Impero la notte di Natale dell'800?", a: "Carlo Magno", p: 300 },
            { q: "In quale battaglia Scipione l'Africano sconfisse definitivamente Annibale?", a: "Battaglia di Zama", p: 300 },
            { q: "Cosa accadde nel 1054 a livello religioso tra la Chiesa di Roma e quella di Costantinopoli?", a: "Il Grande Scisma d'Oriente", p: 300 },
            { q: "In quale anno papa Urbano II bandì la Prima Crociata per la Terrasanta?", a: "1096", p: 300 },
            { q: "Quale sultano d'Egitto e Siria riconquistò Gerusalemme nel 1187?", a: "Saladino", p: 300 },
            { q: "Quale imperatore bizantino promosse la redazione del Corpus Iuris Civilis?", a: "Giustiniano I", p: 300 },
            { q: "Quale battaglia del 732 fermò l'avanzata araba in Europa grazie a Carlo Martello?", a: "Battaglia di Poitiers", p: 300 },
            { q: "Chi fu l'ultima regina d'Egitto della dinastia tolemaica?", a: "Cleopatra", p: 300 },
            // 400
            { q: "Quale storico documento fu concesso dal re inglese Giovanni Senzaterra nel 1215?", a: "Magna Carta", p: 400 },
            { q: "Quale evento storico sancì la fine dell'Impero Bizantino il 29 maggio 1453?", a: "La caduta di Costantinopoli", p: 400 },
            { q: "In quale anno ebbe inizio il conflitto anglo-francese noto come Guerra dei Cent'anni?", a: "1337", p: 400 },
            { q: "In quale anno la Peste Nera iniziò a diffondersi in modo pandemico in Europa?", a: "1347", p: 400 },
            { q: "In quale battaglia del 1415 Enrico V d'Inghilterra sconfisse la cavalleria francese?", a: "Battaglia di Azincourt", p: 400 },
            { q: "Quale battaglia del 1066 segnò la conquista normanna dell'Inghilterra da parte di Guglielmo il Conquistatore?", a: "Battaglia di Hastings", p: 400 },
            { q: "Quale battaglia del 1214, vinta da Filippo II di Francia, è definita la 'prima battaglia europea'?", a: "Battaglia di Bouvines", p: 400 },
            { q: "Quale editto del 313 d.C. concesse la libertà di culto ai cristiani nell'Impero Romano?", a: "Editto di Milano", p: 400 },
            { q: "In quale anno avvenne la vittoria cristiana decisiva contro i musulmani a Las Navas de Tolosa?", a: "1212", p: 400 },
            { q: "Quale anno segna la fine della Guerra delle Due Rose e l'inizio della dinastia Tudor?", a: "1485", p: 400 },
            // 500
            { q: "Quale grande battaglia navale del 1571 vide la flotta cristiana sconfiggere quella ottomana?", a: "Battaglia di Lepanto", p: 500 },
            { q: "Come si chiamava l'ultimo imperatore romano d'Occidente deposto da Odoacre?", a: "Romolo Augustolo", p: 500 },
            { q: "In quale anno si spense a Medina il profeta dell'Islam, Maometto?", a: "632 d.C.", p: 500 },
            { q: "Quale accordo del 1454 fissò per 40 anni gli equilibri tra gli stati regionali italiani?", a: "Pace di Lodi", p: 500 },
            { q: "Quale rovinosa sconfitta bizantina del 1071 contro i Selgiuchidi aprì le porte dell'Anatolia ai Turchi?", a: "Battaglia di Manzicerta", p: 500 },
            { q: "In quale battaglia del 636 d.C. gli eserciti arabi inflissero una sconfitta decisiva ai Bizantini sul fiume?", a: "Battaglia dello Yarmuk", p: 500 },
            { q: "Quale trattato del 1494 divise il Nuovo Mondo tra Spagna e Portogallo?", a: "Trattato di Tordesillas", p: 500 },
            { q: "Quale califfo abbaside fondò a Baghdad la celebre 'Casa della Sapienza'?", a: "Al-Ma'mun", p: 500 },
            { q: "In quale anno il re spartano Leonida e i suoi 300 resistettero ai Persiani alle Termopili?", a: "480 a.C.", p: 500 },
            { q: "Quale tragico evento, perpetrato dai crociati latini, colpì Costantinopoli nel 1204?", a: "Il Sacco di Costantinopoli", p: 500 }
        ]
    },
    {
        id: "hist_modern",
        title: "Storia Mod/Cont.",
        questions: [
            // 100
            { q: "Quale muro che divideva una capitale europea fu abbattuto nel 1989?", a: "Muro di Berlino", p: 100 },
            { q: "Quale grande rivoluzione ebbe inizio il 14 luglio 1789 con la presa della Bastiglia?", a: "Rivoluzione Francese", p: 100 },
            { q: "Come era soprannominato il sovrano francese Luigi XIV?", a: "Re Sole", p: 100 },
            { q: "Quale appellativo latino veniva utilizzato per riferirsi a Benito Mussolini?", a: "Duce", p: 100 },
            { q: "Quale titolo, che significa 'Guida', fu assunto da Adolf Hitler in Germania?", a: "Führer", p: 100 },
            { q: "Chi si autoincoronò Imperatore dei Francesi nel 1804?", a: "Napoleone Bonaparte", p: 100 },
            { q: "In quale anno terminò ufficialmente la Seconda Guerra Mondiale?", a: "1945", p: 100 },
            { q: "Quale patriota italiano è ricordato come l''Eroe dei due mondi'?", a: "Giuseppe Garibaldi", p: 100 },
            { q: "Chi fu il leader incontrastato dell'Unione Sovietica durante la Seconda Guerra Mondiale?", a: "Iosif Stalin", p: 100 },
            { q: "Chi fu il primo Presidente degli Stati Uniti d'America?", a: "George Washington", p: 100 },
            // 200
            { q: "In quale anno fu firmato l'armistizio che pose fine alla Prima Guerra Mondiale?", a: "1918", p: 200 },
            { q: "In quale anno vennero stipulati i Patti Lateranensi tra l'Italia fascista e la Santa Sede?", a: "1929", p: 200 },
            { q: "In quale celebre battaglia del 1815 Napoleone subì la sua sconfitta definitiva?", a: "Battaglia di Waterloo", p: 200 },
            { q: "Quale presidente USA fronteggiò la crisi dei missili di Cuba del 1962?", a: "John F. Kennedy", p: 200 },
            { q: "Quale filosofo ed economista tedesco pubblicò il 'Manifesto del Partito Comunista' nel 1848?", a: "Karl Marx", p: 200 },
            { q: "Quale evento del 1922 portò Benito Mussolini ad ottenere la carica di Presidente del Consiglio?", a: "Marcia su Roma", p: 200 },
            { q: "Tramite quale varco le truppe italiane entrarono a Roma nel 1870, sancendo la fine dello Stato Pontificio?", a: "Breccia di Porta Pia", p: 200 },
            { q: "In quale reggia francese fu firmato il trattato di pace principale alla fine della Prima Guerra Mondiale?", a: "Versailles", p: 200 },
            { q: "Sotto quale sovrana inglese l'Inghilterra sconfisse la 'Invincibile Armata' spagnola?", a: "Elisabetta I", p: 200 },
            { q: "Quale presidente americano guidò l'Unione durante la Guerra di Secessione?", a: "Abraham Lincoln", p: 200 },
            // 300
            { q: "Chi fu il principale leader bolscevico della Rivoluzione d'Ottobre del 1917?", a: "Vladimir Lenin", p: 300 },
            { q: "Quale congresso europeo del 1815 segnò l'inizio della Restaurazione post-napoleonica?", a: "Congresso di Vienna", p: 300 },
            { q: "Come era soprannominato Otto von Bismarck, artefice dell'unificazione tedesca?", a: "Il Cancelliere di Ferro", p: 300 },
            { q: "In quale anno gli italiani scelsero la Repubblica abolendo la monarchia dei Savoia?", a: "1946", p: 300 },
            { q: "In quale anno fu proclamata la nascita dell'Impero Tedesco (II Reich) a Versailles?", a: "1871", p: 300 },
            { q: "Come è noto il grande piano politico-economico statunitense per la ricostruzione dell'Europa nel dopoguerra?", a: "Piano Marshall", p: 300 },
            { q: "Quale statista piemontese fu il principale artefice politico dell'Unità d'Italia?", a: "Camillo Benso, conte di Cavour", p: 300 },
            { q: "In quale anno i Trattati di Roma istituirono la Comunità Economica Europea (CEE)?", a: "1957", p: 300 },
            { q: "Su quale città giapponese fu sganciata la prima bomba atomica il 6 agosto 1945?", a: "Hiroshima", p: 300 },
            { q: "Chi fu il leader del movimento non-violento che portò all'indipendenza dell'India?", a: "Mahatma Gandhi", p: 300 },
            // 400
            { q: "Quali paci del 1648 posero fine alla disastrosa Guerra dei Trent'anni in Europa?", a: "Paci di Vestfalia", p: 400 },
            { q: "Quale evento del 1618 scatenò l'inizio della Guerra dei Trent'anni?", a: "Defenestrazione di Praga", p: 400 },
            { q: "Con quale rivoluzionario accordo l'Egitto e Israele firmarono la pace a Camp David nel 1978? (Presidente egiziano)", a: "Anwar al-Sadat", p: 400 },
            { q: "Quale generale guidò le forze della 'Francia Libera' durante l'occupazione nazista?", a: "Charles de Gaulle", p: 400 },
            { q: "In quale località crimeana si incontrarono Churchill, Roosevelt e Stalin nel febbraio 1945?", a: "Yalta", p: 400 },
            { q: "Quale politico francese fu il principale protagonista del periodo del 'Terrore' giacobino?", a: "Maximilien de Robespierre", p: 400 },
            { q: "Quale conflitto (1853-1856) vide l'Impero Russo opposto a un'alleanza di Ottomani, Francesi, Inglesi e Piemontesi?", a: "Guerra di Crimea", p: 400 },
            { q: "Quale premier britannico promise 'sangue, fatica, lacrime e sudore' affrontando il nazismo?", a: "Winston Churchill", p: 400 },
            { q: "La spedizione di quale esploratore portoghese compì la prima circumnavigazione del globo?", a: "Ferdinando Magellano", p: 400 },
            { q: "In quale anno Martin Lutero affisse le sue 95 Tesi, avviando la Riforma Protestante?", a: "1517", p: 400 },
            // 500
            { q: "In quale data esatta (giorno/mese/anno) venne formalmente proclamato il Regno d'Italia?", a: "17 marzo 1861", p: 500 },
            { q: "Quale armistizio del 1859 interruppe bruscamente la Seconda Guerra d'Indipendenza italiana?", a: "Armistizio di Villafranca", p: 500 },
            { q: "In quale data esatta (giorno/mese/anno) fu combattuta la battaglia di Waterloo?", a: "18 giugno 1815", p: 500 },
            { q: "Quale trattato del 1713 pose fine alla Guerra di Successione Spagnola?", a: "Trattato di Utrecht", p: 500 },
            { q: "Quali accordi del 1678 misero fine alla Guerra d'Olanda tra Luigi XIV e la coalizione alleata?", a: "Pace di Nimega", p: 500 },
            { q: "In quale anno avvenne in Inghilterra la cosiddetta 'Gloriosa Rivoluzione'?", a: "1688", p: 500 },
            { q: "In quale arco temporale (anni) fu combattuta la Guerra dei Sette Anni, definita da Churchill 'la vera prima guerra mondiale'?", a: "1756-1763", p: 500 },
            { q: "In quale famosa battaglia del 1813, nota come 'Battaglia delle Nazioni', Napoleone venne duramente sconfitto?", a: "Battaglia di Lipsia", p: 500 },
            { q: "Quale trattato del 1918 sancì l'uscita anticipata della Russia sovietica dalla Prima Guerra Mondiale?", a: "Trattato di Brest-Litovsk", p: 500 },
            { q: "Come è noto il patto di non aggressione del 1939 stipulato tra Germania Nazista e Unione Sovietica?", a: "Patto Molotov-Ribbentrop", p: 500 }
        ]
    },
    {
        id: "phil",
        title: "Filosofia",
        questions: [
            // 100
            { q: "Chi è l'autore del celebre dialogo filosofico intitolato 'La Repubblica'?", a: "Platone", p: 100 },
            { q: "Quale filosofo ha pronunciato la massima 'Cogito ergo sum' (Penso, dunque sono)?", a: "René Descartes (Cartesio)", p: 100 },
            { q: "A quale pensatore antico è attribuita la consapevolezza di 'sapere di non sapere'?", a: "Socrate", p: 100 },
            { q: "Quale grande filosofo greco fondò ad Atene la scuola peripatetica nota come il 'Liceo'?", a: "Aristotele", p: 100 },
            { q: "Quale filosofo tedesco dell'Ottocento ha proclamato che 'Dio è morto'?", a: "Friedrich Nietzsche", p: 100 },
            { q: "Chi ha scritto il celebre trattato politico 'Il Principe'?", a: "Niccolò Machiavelli", p: 100 },
            { q: "Quale filosofo dell'antichità ha esposto il 'Mito della Caverna'?", a: "Platone", p: 100 },
            { q: "Quale filosofo francese è spesso considerato il padre della filosofia moderna?", a: "René Descartes (Cartesio)", p: 100 },
            { q: "Come chiamava Socrate il suo metodo di indagine basato sul dialogo per 'far partorire' la verità?", a: "Maieutica", p: 100 },
            { q: "Quale umanista inglese scrisse l'opera 'Utopia' immaginando una società ideale?", a: "Tommaso Moro", p: 100 },
            // 200
            { q: "Quale illuminista tedesco è l'autore della 'Critica della ragion pura'?", a: "Immanuel Kant", p: 200 },
            { q: "Quale principio logico di parsimonia è noto come il 'Rasoio di...'?", a: "Guglielmo di Ockham", p: 200 },
            { q: "Quale filosofo inglese scrisse il 'Leviatano' per teorizzare lo Stato assoluto?", a: "Thomas Hobbes", p: 200 },
            { q: "Quale famosa opera pubblicò Cartesio nel 1637 per porre le basi del suo pensiero razionalista?", a: "Discorso sul metodo", p: 200 },
            { q: "Quale filosofo inglese fondò l'empirismo moderno col 'Saggio sull'intelletto umano'?", a: "John Locke", p: 200 },
            { q: "Quale filosofo utilizzò il concetto orientale del 'Velo di Maya' per indicare l'illusorietà del mondo fenomenico?", a: "Arthur Schopenhauer", p: 200 },
            { q: "In quale dialogo platonico i personaggi discutono della natura dell'Eros (Amore)?", a: "Il Simposio", p: 200 },
            { q: "Quale trattato di etica scrisse Aristotele dedicandolo a suo figlio?", a: "Etica Nicomachea", p: 200 },
            { q: "Con la frase 'Homo homini lupus' Hobbes descriveva lo stato di natura. Cosa significa?", a: "L'uomo è un lupo per l'altro uomo", p: 200 },
            { q: "Quale filosofo danese è considerato il precursore dell'esistenzialismo?", a: "Søren Kierkegaard", p: 200 },
            // 300
            { q: "Quali sono i tre stadi della vita teorizzati da Søren Kierkegaard?", a: "Estetico, Etico e Religioso", p: 300 },
            { q: "Come chiamava Francis Bacon i pregiudizi e gli errori che ostacolano la conoscenza umana?", a: "Idòla", p: 300 },
            { q: "Quale opera di Nietzsche introduce la figura dell'Oltreuomo (Übermensch) ed è 'un libro per tutti e per nessuno'?", a: "Così parlò Zarathustra", p: 300 },
            { q: "Quale filosofo presocratico è associato alla dottrina del 'Panta Rhei' (Tutto scorre)?", a: "Eraclito", p: 300 },
            { q: "Quale vescovo di Ippona scrisse il trattato teologico 'La città di Dio'?", a: "Sant'Agostino", p: 300 },
            { q: "Come si chiamano le entità spirituali indivisibili teorizzate dal filosofo Leibniz?", a: "Monadi", p: 300 },
            { q: "Chi è l'autore del saggio politico 'Il contratto sociale' del 1762?", a: "Jean-Jacques Rousseau", p: 300 },
            { q: "Chi fu, assieme a d'Alembert, il principale curatore dell'Encyclopédie illuminista?", a: "Denis Diderot", p: 300 },
            { q: "Quale filosofo olandese teorizzò una visione panteistica in cui Dio coincide con la Natura ('Deus sive Natura')?", a: "Baruch Spinoza", p: 300 },
            { q: "In quale sua celebre opera Sant'Agostino racconta la sua tormentata conversione al Cristianesimo?", a: "Le Confessioni", p: 300 },
            // 400
            { q: "Quale termine tedesco, che significa 'Esserci', usò Heidegger per descrivere l'esistenza umana?", a: "Dasein", p: 400 },
            { q: "Quale filosofo austriaco scrisse il 'Tractatus logico-philosophicus'?", a: "Ludwig Wittgenstein", p: 400 },
            { q: "Quale opera fondamentale dell'idealismo tedesco fu pubblicata da Hegel nel 1807?", a: "Fenomenologia dello spirito", p: 400 },
            { q: "Quale celebre 'dialettica' hegeliana descrive il conflitto per il riconoscimento che porta uno a dominare l'altro?", a: "Dialettica Servo-Padrone", p: 400 },
            { q: "Quale filosofo esistenzialista francese è l'autore del saggio 'L'essere e il nulla'?", a: "Jean-Paul Sartre", p: 400 },
            { q: "Quale celebre romanzo di Sartre esplora il senso di assurdità dell'esistenza provato dal protagonista Roquentin?", a: "La Nausea", p: 400 },
            { q: "Con quale titolo generale fu poi raggruppato l'insieme degli scritti logici di Aristotele?", a: "Organon", p: 400 },
            { q: "Qual è il capolavoro filosofico scritto da Arthur Schopenhauer nel 1819?", a: "Il mondo come volontà e rappresentazione", p: 400 },
            { q: "In quale opera postuma Wittgenstein confuta il suo stesso pensiero precedente, introducendo i 'giochi linguistici'?", a: "Ricerche Filosofiche", p: 400 },
            { q: "Cosa indicano gli 'Idola Tribus' nella classificazione dei pregiudizi fatta da Bacone?", a: "I pregiudizi intrinseci alla natura della specie umana", p: 400 },
            // 500
            { q: "Quale concetto etico kantiano richiede di agire affinché la massima della propria azione possa divenire legge universale?", a: "Imperativo Categorico", p: 500 },
            { q: "Qual è l'opera principale di Spinoza, esposta usando assiomi, definizioni e dimostrazioni come in geometria?", a: "Ethica ordine geometrico demonstrata", p: 500 },
            { q: "In quale breve opera Leibniz espone in modo riassuntivo la sua metafisica nel 1714?", a: "Monadologia", p: 500 },
            { q: "Qual è il titolo della monumentale opera incompiuta in cui Tommaso d'Aquino sintetizza la teologia cristiana con Aristotele?", a: "Summa Theologiae", p: 500 },
            { q: "Quale dottrina nietzschiana immagina che l'esistenza si ripeta infinite volte esattamente identica a sé stessa?", a: "L'Eterno Ritorno dell'Uguale", p: 500 },
            { q: "Qual è il titolo del capolavoro incompiuto pubblicato nel 1927 da Martin Heidegger?", a: "Essere e Tempo (Sein und Zeit)", p: 500 },
            { q: "Quale termine usa Kant per definire la 'cosa in sé', inconoscibile per la mente umana a differenza del fenomeno?", a: "Noumeno", p: 500 },
            { q: "Quali e quante sono le 'radici' fondamentali teorizzate dal filosofo Empedocle per formare ogni cosa?", a: "4 (Fuoco, Aria, Acqua, Terra)", p: 500 },
            { q: "Quale opera di Bacone del 1620 ambiva a rimpiazzare la logica aristotelica con un nuovo metodo induttivo?", a: "Novum Organum", p: 500 },
            { q: "Quale schema di ragionamento logico a tre proposizioni (due premesse e una conclusione) fu teorizzato da Aristotele?", a: "Sillogismo", p: 500 }
        ]
    },
    {
        id: "math",
        title: "Matematica",
        questions: [
            // 100
            { q: "Qual è la derivata prima della funzione f(x) = x²?", a: "2x", p: 100 },
            { q: "Qual è la somma degli angoli interni di un qualsiasi triangolo piano?", a: "180 gradi", p: 100 },
            { q: "La formula 'π * r²' permette di calcolare cosa?", a: "L'area di un cerchio", p: 100 },
            { q: "Come è chiamato un numero naturale maggiore di 1 che è divisibile solo per 1 e per sé stesso?", a: "Numero Primo", p: 100 },
            { q: "Qual è la radice quadrata di 144?", a: "12", p: 100 },
            { q: "Qual è la derivata di una costante k rispetto alla variabile x?", a: "0", p: 100 },
            { q: "Cosa si calcola con la formula '(base * altezza) / 2'?", a: "L'area di un triangolo", p: 100 },
            { q: "Quale teorema per i triangoli rettangoli si esprime con 'a² + b² = c²'?", a: "Teorema di Pitagora", p: 100 },
            { q: "Cosa si calcola moltiplicando '2 * π * r'?", a: "La circonferenza (o perimetro) di un cerchio", p: 100 },
            { q: "Il numero 6 è considerato un numero perfetto (somma dei suoi divisori propri uguali a sé stesso)?", a: "Sì", p: 100 },
            // 200
            { q: "Qual è la derivata prima della funzione sin(x)?", a: "cos(x)", p: 200 },
            { q: "A quanto equivale approssimativamente alle prime due cifre decimali il Numero di Nepero (e)?", a: "2.71", p: 200 },
            { q: "Qual è la derivata prima della funzione cos(x)?", a: "-sin(x)", p: 200 },
            { q: "Quale figura geometrica ha area pari a '(Base maggiore + base minore) * altezza / 2'?", a: "Trapezio", p: 200 },
            { q: "Qual è la formula del discriminante (Delta) di un'equazione di secondo grado ax² + bx + c = 0?", a: "b² - 4ac", p: 200 },
            { q: "Qual è la derivata prima della funzione f(x) = e^x?", a: "e^x", p: 200 },
            { q: "Qual è l'inverso moltiplicativo (o reciproco) della frazione 2/3?", a: "3/2", p: 200 },
            { q: "A quanto equivale il logaritmo naturale del numero di Nepero, ln(e)?", a: "1", p: 200 },
            { q: "Come si chiama la semiretta che divide un angolo in due angoli di uguale ampiezza?", a: "Bisettrice", p: 200 },
            { q: "Come si definisce un angolo che misura più di 90° ma meno di 180°?", a: "Ottuso", p: 200 },
            // 300
            { q: "Qual è la derivata prima della funzione logaritmo naturale ln(x)?", a: "1/x", p: 300 },
            { q: "Qual è il logaritmo in base 10 di 1000?", a: "3", p: 300 },
            { q: "A cosa è uguale l'espansione del quadrato di binomio (a + b)²?", a: "a² + 2ab + b²", p: 300 },
            { q: "Quale metodo sviluppato da Eudosso e perfezionato da Archimede prefigura il calcolo integrale per l'area delle figure curve?", a: "Metodo di esaustione", p: 300 },
            { q: "Qual è la formula per calcolare il volume di una sfera di raggio r?", a: "(4/3) * π * r³", p: 300 },
            { q: "Qual è il limite per x che tende a 0 del rapporto sin(x)/x?", a: "1", p: 300 },
            { q: "Come si chiama in analisi matematica una retta a cui la curva di una funzione si avvicina indefinitamente senza mai toccarla?", a: "Asintoto", p: 300 },
            { q: "Come si definisce una funzione che è sia iniettiva che suriettiva?", a: "Biunivoca (o Biiettiva)", p: 300 },
            { q: "Qual è la derivata della funzione tangente tan(x)?", a: "1/cos²(x) (oppure 1 + tan²(x))", p: 300 },
            { q: "Qual è la formula chiusa per la somma dei primi n numeri interi (1+2+...+n)?", a: "n(n+1)/2", p: 300 },
            // 400
            { q: "Quale logico austriaco formulò i celebri Teoremi di Incompletezza nel 1931?", a: "Kurt Gödel", p: 400 },
            { q: "A quale valore decimale corrisponde approssimativamente la Sezione Aurea (Phi)?", a: "1.618", p: 400 },
            { q: "Nel calcolo integrale per parti, a cosa è uguale l'integrale di u dv?", a: "uv - integrale di v du", p: 400 },
            { q: "Qual è il risultato della celebre Identità di Eulero e^(iπ) + 1?", a: "0", p: 400 },
            { q: "Qual è la derivata prima della funzione arcocoseno, arccos(x)?", a: "-1/√(1-x²)", p: 400 },
            { q: "Come si chiama un punto in cui una curva cambia la propria concavità?", a: "Punto di flesso", p: 400 },
            { q: "Nell'algebra astratta, se un gruppo possiede l'operazione commutativa, esso viene detto Gruppo...?", a: "Abeliano", p: 400 },
            { q: "Quale matematico tedesco è considerato il co-inventore del calcolo infinitesimale assieme a Isaac Newton?", a: "Gottfried Wilhelm von Leibniz", p: 400 },
            { q: "Come viene chiamata una Serie di Taylor in cui il punto di sviluppo è centrato in x = 0?", a: "Serie di Maclaurin", p: 400 },
            { q: "Quale matematico rinascimentale italiano pubblicò la formula risolutiva per le equazioni di terzo grado nell'Ars Magna?", a: "Gerolamo Cardano", p: 400 },
            // 500
            { q: "Come è noto l'enunciato secondo cui x^n + y^n = z^n non ha soluzioni intere positive se n > 2?", a: "Ultimo Teorema di Fermat", p: 500 },
            { q: "Quale matematico britannico dimostrò formalmente l'Ultimo Teorema di Fermat nel 1994?", a: "Andrew Wiles", p: 500 },
            { q: "L'Ipotesi più celebre della matematica non dimostrata collega i numeri primi agli zeri non banali di quale Funzione formulata da un matematico tedesco?", a: "Funzione Zeta (Ipotesi di Riemann)", p: 500 },
            { q: "In quale successione ogni numero (dopo i primi due) è la somma dei due numeri immediatamente precedenti?", a: "Successione di Fibonacci", p: 500 },
            { q: "Quale congettura irrisolta afferma che ogni numero pari maggiore di 2 può essere scritto come somma di due numeri primi?", a: "Congettura di Goldbach", p: 500 },
            { q: "Come si chiama una figura geometrica complessa dotata della proprietà di autosimilarità a qualsiasi scala di ingrandimento?", a: "Frattale", p: 500 },
            { q: "Come si chiama la rigorosa definizione del limite in analisi matematica, introdotta da Cauchy e Weierstrass?", a: "Definizione Epsilon-Delta", p: 500 },
            { q: "Quale matematico italiano del XVI secolo formalizzò le prime regole per operare con i numeri immaginari?", a: "Rafael Bombelli", p: 500 },
            { q: "Quale teorema asserisce che un polinomio di grado 'n' ha esattamente 'n' radici nel campo dei numeri complessi?", a: "Teorema Fondamentale dell'Algebra", p: 500 },
            { q: "Quale equazione matematica viene spesso definita la 'più bella della matematica' per legare 5 costanti fondamentali (e, i, π, 1, 0)?", a: "Identità di Eulero", p: 500 }
        ]
    },
    {
        id: "inf",
        title: "Informatica",
        questions: [
            // 100
            { q: "Quale unità fondamentale di informazione può assumere esclusivamente il valore 0 o il valore 1?", a: "Bit", p: 100 },
            { q: "Chi è l'informatico britannico considerato l'inventore del World Wide Web (WWW)?", a: "Tim Berners-Lee", p: 100 },
            { q: "La RAM è un tipo di memoria detta 'volatile'. Cosa significa in termini pratici?", a: "Che perde i dati quando si toglie la corrente", p: 100 },
            { q: "Quale componente è spesso definito il 'cervello' del computer, incaricato dell'elaborazione (sigla in inglese)?", a: "CPU (Central Processing Unit)", p: 100 },
            { q: "Cosa significa la sigla 'USB' utilizzata per indicare lo standard di connessione periferica?", a: "Universal Serial Bus", p: 100 },
            { q: "Quale componente del PC è la principale 'memoria di massa' in cui vengono salvati i file a lungo termine?", a: "Disco Rigido / Hard Disk (o SSD)", p: 100 },
            { q: "Quale periferica di input, inventata da Douglas Engelbart, controlla il puntatore a schermo?", a: "Mouse", p: 100 },
            { q: "Come si chiama la categoria di software (es. Chrome, Firefox, Safari) utilizzati per navigare sul web?", a: "Browser", p: 100 },
            { q: "Quale periferica serve per inserire testo e comandi digitando su dei tasti?", a: "Tastiera (Keyboard)", p: 100 },
            { q: "Cosa indica l'acronimo OS in ambito informatico (ad es. Windows, macOS)?", a: "Operating System (Sistema Operativo)", p: 100 },
            // 200
            { q: "In quale linguaggio di programmazione è quasi interamente scritto il kernel del sistema operativo Linux?", a: "C", p: 200 },
            { q: "Quale protocollo traduce i nomi di dominio (es. google.com) nei relativi indirizzi IP numerici?", a: "DNS (Domain Name System)", p: 200 },
            { q: "Quale protocollo di rete viene tipicamente utilizzato per il trasferimento di file tra client e server (sigla)?", a: "FTP (File Transfer Protocol)", p: 200 },
            { q: "Quale linguaggio di markup, basato sui tag, costituisce la struttura di base delle pagine web?", a: "HTML", p: 200 },
            { q: "Cosa significa la sigla 'IP' nell'indirizzo numerico di una connessione internet?", a: "Internet Protocol", p: 200 },
            { q: "Quale linguaggio (acronimo a 3 lettere) viene usato per definire la formattazione e lo stile visivo dei documenti HTML?", a: "CSS (Cascading Style Sheets)", p: 200 },
            { q: "Quale diffusissimo linguaggio di scripting rende interattive le pagine web all'interno dei browser?", a: "JavaScript", p: 200 },
            { q: "Come si chiama la truffa informatica in cui si inviano finte email per rubare credenziali bancarie?", a: "Phishing", p: 200 },
            { q: "Quale sistema di sicurezza monitora e controlla il traffico di rete in entrata e in uscita creando un 'muro di fuoco'?", a: "Firewall", p: 200 },
            { q: "Quale dispositivo di rete è responsabile di instradare i pacchetti dati da una rete locale a internet?", a: "Router", p: 200 },
            // 300
            { q: "Quale componente hardware (sigla) è dedicato all'accelerazione del rendering delle immagini e della grafica 3D?", a: "GPU (Graphics Processing Unit)", p: 300 },
            { q: "Presso quale centro di ricerca europeo è nato il World Wide Web nel 1989?", a: "CERN di Ginevra", p: 300 },
            { q: "Quale matematico ottocentesco progettò la 'Macchina Analitica', vero e proprio precursore del computer?", a: "Charles Babbage", p: 300 },
            { q: "Chi è il programmatore olandese che nel 1991 ha creato il linguaggio di programmazione Python?", a: "Guido van Rossum", p: 300 },
            { q: "Qual è il linguaggio standard (acronimo a 3 lettere) utilizzato per interagire e interrogare i database relazionali?", a: "SQL (Structured Query Language)", p: 300 },
            { q: "Nel sistema numerico binario, quale base matematica viene utilizzata?", a: "Base 2", p: 300 },
            { q: "Come si chiama il programma che traduce un intero codice sorgente in linguaggio macchina prima dell'esecuzione?", a: "Compilatore (Compiler)", p: 300 },
            { q: "Cosa significa l'acronimo SSD che identifica le moderne unità di archiviazione veloci?", a: "Solid State Drive (Unità a stato solido)", p: 300 },
            { q: "Di quanti bit è composto convenzionalmente un Byte?", a: "8", p: 300 },
            { q: "Quale codice standard a 7 bit venne sviluppato nel 1963 per rappresentare i caratteri testuali nei computer?", a: "ASCII", p: 300 },
            // 400
            { q: "L'algoritmo di crittografia RSA utilizza una chiave pubblica e una privata. È quindi a crittografia simmetrica o asimmetrica?", a: "Asimmetrica", p: 400 },
            { q: "Quale fu il primo linguaggio di programmazione ad alto livello della storia, creato nel 1957 all'IBM?", a: "Fortran", p: 400 },
            { q: "Chi è lo studente finlandese che nel 1991 annunciò la creazione di un nuovo kernel libero e open source?", a: "Linus Torvalds", p: 400 },
            { q: "Quali due ingegneri informatici americani svilupparono la suite di protocolli TCP/IP alla base di Internet?", a: "Vint Cerf e Bob Kahn", p: 400 },
            { q: "Come viene definito il nucleo centrale di un sistema operativo che ha il controllo completo su tutto l'hardware?", a: "Kernel", p: 400 },
            { q: "Quale celebre piattaforma open source utilizza la tecnologia della 'containerizzazione' tramite un'icona a forma di balena?", a: "Docker", p: 400 },
            { q: "Quale diffuso sistema di controllo di versione distribuito fu creato da Linus Torvalds nel 2005?", a: "Git", p: 400 },
            { q: "Come si definisce il ritardo di tempo impiegato da un pacchetto dati per viaggiare dal mittente al destinatario?", a: "Latenza (Latency / Ping)", p: 400 },
            { q: "Cosa significa la sigla API, fondamentale per far comunicare software diversi?", a: "Application Programming Interface", p: 400 },
            { q: "Quale leggero formato testuale di interscambio dati utilizza coppie chiave-valore derivate da JavaScript?", a: "JSON", p: 400 },
            // 500
            { q: "Chi è considerata la prima programmatrice della storia per il suo algoritmo destinato alla Macchina Analitica nel 1843?", a: "Ada Lovelace", p: 500 },
            { q: "Come è chiamato il famoso esperimento mentale proposto nel 1950 per determinare se una macchina possiede un'intelligenza indistinguibile da un umano?", a: "Test di Turing", p: 500 },
            { q: "Presso quali celebri laboratori venne sviluppato nel 1969 il sistema operativo Unix?", a: "Bell Labs", p: 500 },
            { q: "Quale macchina cifrante tedesca venne decrittata dal team di Alan Turing a Bletchley Park durante la II Guerra Mondiale?", a: "Enigma", p: 500 },
            { q: "Qual è il più celebre problema irrisolto del Clay Mathematics Institute riguardante i tempi di risoluzione degli algoritmi?", a: "P vs NP", p: 500 },
            { q: "Come si chiama l'unità di informazione fondamentale utilizzata nei computer quantistici?", a: "Qubit (Quantum bit)", p: 500 },
            { q: "A quale scienziato è intitolata l'architettura logica su cui si basano la quasi totalità dei computer moderni?", a: "John von Neumann", p: 500 },
            { q: "Quale linguaggio di programmazione funzionale, pioniere nell'IA, fu creato da John McCarthy nel 1958?", a: "LISP", p: 500 },
            { q: "Quale famosa 'legge' empirica afferma che il numero di transistor in un microprocessore raddoppia circa ogni due anni?", a: "Legge di Moore", p: 500 },
            { q: "Quale sotto-ramo del Machine Learning utilizza Reti Neurali Artificiali con numerosi strati (layers) nascosti?", a: "Deep Learning", p: 500 }
        ]
    },
    {
        id: "anime",
        title: "Anime & Manga",
        questions: [
            // 100
            { q: "Di quale manga creato da Eiichirō Oda è protagonista il pirata Monkey D. Luffy?", a: "One Piece", p: 100 },
            { q: "A quale popolarissimo franchise appartiene il topo elettrico giallo Pikachu?", a: "Pokémon", p: 100 },
            { q: "Chi è il creatore del celeberrimo manga shonen Dragon Ball?", a: "Akira Toriyama", p: 100 },
            { q: "Come si chiama il giovane ninja biondo del Villaggio della Foglia che sogna di diventare Hokage?", a: "Naruto Uzumaki", p: 100 },
            { q: "Come si chiama il gatto robot spaziale di colore azzurro e senza orecchie inventato da Fujiko F. Fujio?", a: "Doraemon", p: 100 },
            { q: "Qual è il nome terrestre del guerriero Saiyan protagonista di Dragon Ball?", a: "Goku (Kakaroth)", p: 100 },
            { q: "Come si fa chiamare il brillante liceale rimpicciolito in bambino nel manga 'Detective... '?", a: "Conan (Edogawa)", p: 100 },
            { q: "Dietro il nome in codice di 'Kira' si nasconde l'identità di quale liceale possessore del Death Note?", a: "Light Yagami", p: 100 },
            { q: "Quale fumettista giapponese, padre dei mecha, ha creato Mazinga Z, Goldrake e Jeeg?", a: "Go Nagai", p: 100 },
            { q: "Qual è il nome della guerriera vestita alla marinara che si trasforma in Sailor Moon?", a: "Usagi Tsukino (Bunny in italiano)", p: 100 },
            // 200
            { q: "Quale celebre Studio di animazione giapponese è stato co-fondato da Hayao Miyazaki e Isao Takahata?", a: "Studio Ghibli", p: 200 },
            { q: "Quale oscuro oggetto sovrannaturale uccide chiunque vi abbia scritto il proprio nome all'interno?", a: "Death Note", p: 200 },
            { q: "Qual è il nome del tormentato quattordicenne pilota dell'unità Eva-01 in Neon Genesis Evangelion?", a: "Shinji Ikari", p: 200 },
            { q: "Quale mangaka detiene il Guinness World Record per la serie a fumetti con più copie pubblicate da un singolo autore (One Piece)?", a: "Eiichirō Oda", p: 200 },
            { q: "Come si chiama lo Shinigami (Dio della Morte) dai capelli arancioni protagonista di Bleach?", a: "Ichigo Kurosaki", p: 200 },
            { q: "Come si chiamano i giganteschi umanoidi bio-meccanici impiegati per difendere Neo Tokyo-3 in Evangelion?", a: "Evangelion (Eva)", p: 200 },
            { q: "Quale capolavoro di Takehiko Inoue è universalmente riconosciuto come il manga definitivo sul basket liceale?", a: "Slam Dunk", p: 200 },
            { q: "Come si chiama il giovane Alchimista di Stato che ha perso un braccio e una gamba in Fullmetal Alchemist?", a: "Edward Elric", p: 200 },
            { q: "Qual è il nome del 'Guerriero Nero' armato dello spadone Ammazzadraghi, protagonista di Berserk?", a: "Guts (Gatsu)", p: 200 },
            { q: "Quale grosso e peloso spirito della foresta, armato di ombrello e foglia, è divenuto il logo dello Studio Ghibli?", a: "Totoro", p: 200 },
            // 300
            { q: "In Neon Genesis Evangelion, chi è il pilota dell'Unità Eva-01?", a: "Shinji Ikari", p: 300 },
            { q: "Chi è l'amato mangaka che ha scritto e disegnato l'epopea dark fantasy Berserk?", a: "Kentaro Miura", p: 300 },
            { q: "Quale geniale e stravagante detective, amante dei dolciumi, dà la caccia a Kira in Death Note?", a: "L (L Lawliet)", p: 300 },
            { q: "Quale visionario regista ha diretto film animati del calibro di Perfect Blue, Paprika e Tokyo Godfathers?", a: "Satoshi Kon", p: 300 },
            { q: "In quale anno è iniziata la lunghissima serializzazione di One Piece sulla rivista Shonen Jump?", a: "1997", p: 300 },
            { q: "Quale mangaka è sia l'autore del manga che il regista del rivoluzionario film cyberpunk Akira?", a: "Katsuhiro Otomo", p: 300 },
            { q: "Come si chiama l'ex sicario spaziale, praticante il Jeet Kune Do, protagonista di Cowboy Bebop?", a: "Spike Spiegel", p: 300 },
            { q: "Quale immortale mangaka continua dal 1987 la serializzazione de 'Le bizzarre avventure di JoJo'?", a: "Hirohiko Araki", p: 300 },
            { q: "Qual è il nome dell'invincibile vampiro protagonista di Hellsing, che lavora per Integra Fairbrook Wingates?", a: "Alucard", p: 300 },
            { q: "In quale anno venne trasmesso in Giappone il primissimo storico anime di Mobile Suit Gundam?", a: "1979", p: 300 },
            // 400
            { q: "Quale geniale autore di thriller psicologici a fumetti ha creato Monster e 20th Century Boys?", a: "Naoki Urasawa", p: 400 },
            { q: "Quale celebre studio d'animazione giapponese produsse Cowboy Bebop e la serie Gundam?", a: "Sunrise", p: 400 },
            { q: "Quale regista diresse l'influente adattamento cinematografico di Ghost in the Shell del 1995?", a: "Mamoru Oshii", p: 400 },
            { q: "Quale celebre manga ecologista-fantascientifico fu pubblicato da Hayao Miyazaki prima di fondare lo Studio Ghibli?", a: "Nausicaä della Valle del vento", p: 400 },
            { q: "Quale leggendario autore ha creato il cupo demone Akira Fudo, protagonista di Devilman?", a: "Go Nagai", p: 400 },
            { q: "Quale studio d'animazione indipendente produsse l'iconico Neon Genesis Evangelion e Gurren Lagann?", a: "Gainax", p: 400 },
            { q: "In quale gigantesca città post-apocalittica si svolgono gli eventi principali di Akira?", a: "Neo Tokyo", p: 400 },
            { q: "Come si chiama il solitario viaggiatore studioso di creature invisibili, protagonista di Mushishi?", a: "Ginko", p: 400 },
            { q: "Quale maestro dello stile visivo autoriale ha disegnato Ping Pong e Tekkonkinkreet?", a: "Taiyo Matsumoto", p: 400 },
            { q: "In quale anno debuttò nelle sale cinematografiche il film d'animazione Akira?", a: "1988", p: 400 },
            // 500
            { q: "In quale anno è stato pubblicato il primissimo volume tankobon del manga Berserk?", a: "1989", p: 500 },
            { q: "Come si chiama la cyborg Maggiore protagonista delle indagini in Ghost in the Shell?", a: "Motoko Kusanagi", p: 500 },
            { q: "Quale eclettico regista ha diretto le acclamate serie Cowboy Bebop e Samurai Champloo?", a: "Shin'ichirō Watanabe", p: 500 },
            { q: "Quale incontrastato maestro del manga horror contemporaneo ha scritto l'inquietante opera 'Uzumaki' (Spirale)?", a: "Junji Ito", p: 500 },
            { q: "In quale anno i lettori di tutto il mondo hanno pianto l'improvvisa scomparsa dell'autore di Berserk, Kentaro Miura?", a: "2021", p: 500 },
            { q: "Quale storico studio di animazione realizzò l'incredibile impalcatura visiva del film Akira?", a: "Tokyo Movie Shinsha (TMS Entertainment)", p: 500 },
            { q: "Quale capolavoro artistico di Takehiko Inoue racconta in forma romanzata la vita dello spadaccino Miyamoto Musashi?", a: "Vagabond", p: 500 },
            { q: "Qual è il titolo originale giapponese del seminale manga sulla boxe noto in Italia come Rocky Joe?", a: "Ashita no Joe (Joe del domani)", p: 500 },
            { q: "Quale visionario film d'animazione di Satoshi Kon ruota attorno all'omonima 'detective dei sogni' in cura psicologica?", a: "Paprika - Sognando un sogno", p: 500 },
            { q: "Quale iconico anime OVA sci-fi della Gainax, diretto da Hideaki Anno, affronta in modo struggente la dilatazione del tempo spaziale?", a: "Punta al Top! Gunbuster", p: 500 }
        ]
    },
    {
        id: "geo",
        title: "Geografia",
        questions: [
            // 100
            { q: "Qual è lo stato che ha recentemente superato la Cina come paese più popoloso del mondo?", a: "India", p: 100 },
            { q: "Di quale nazione europea Madrid è la capitale?", a: "Spagna", p: 100 },
            { q: "Qual è il fiume più lungo interamente compreso nel territorio dell'Italia?", a: "Po", p: 100 },
            { q: "Come si chiama il vastissimo deserto che occupa il nord del continente africano?", a: "Deserto del Sahara", p: 100 },
            { q: "Quale città italiana ospita al suo interno il piccolo Stato della Città del Vaticano?", a: "Roma", p: 100 },
            { q: "Di quale grande nazione europea Parigi è la capitale?", a: "Francia", p: 100 },
            { q: "Quale metropoli è la capitale del Regno Unito di Gran Bretagna e Irlanda del Nord?", a: "Londra", p: 100 },
            { q: "Quale grande città europea, divisa da un muro fino al 1989, è la capitale della Germania?", a: "Berlino", p: 100 },
            { q: "Di quale nazione asiatica Tokyo è la grande e densamente popolata capitale?", a: "Giappone", p: 100 },
            { q: "Quale città sorge sul fiume Potomac ed è la capitale federale degli Stati Uniti d'America?", a: "Washington D.C.", p: 100 },
            // 200
            { q: "Quale famoso stretto marittimo separa l'Asia (Russia) dall'America del Nord (Alaska)?", a: "Stretto di Bering", p: 200 },
            { q: "Quale nazione euro-asiatica detiene il primato come paese più vasto del mondo?", a: "Russia", p: 200 },
            { q: "Non è né Sydney né Melbourne, qual è la capitale ufficiale dell'Australia?", a: "Canberra", p: 200 },
            { q: "Quale stretto mette in comunicazione il Mar Mediterraneo con l'Oceano Atlantico?", a: "Stretto di Gibilterra", p: 200 },
            { q: "Qual è la capitale federale del Canada, situata nella provincia dell'Ontario?", a: "Ottawa", p: 200 },
            { q: "Quale città fu costruita da zero a forma di aeroplano per diventare la nuova capitale del Brasile nel 1960?", a: "Brasilia", p: 200 },
            { q: "Quale lungo fiume africano attraversa l'Egitto sfociando a delta nel Mediterraneo?", a: "Nilo", p: 200 },
            { q: "Quale immensa catena montuosa percorre la costa occidentale del Sud America?", a: "Cordigliera delle Ande", p: 200 },
            { q: "Quale immensa catena montuosa asiatica separa il subcontinente indiano dall'altopiano tibetano?", a: "Himalaya", p: 200 },
            { q: "Quale importante fiume attraversa la città di Londra prima di sfociare nel Mare del Nord?", a: "Tamigi", p: 200 },
            // 300
            { q: "Quale monte situato in Argentina, nelle Ande, è la cima più elevata del continente americano (6960m)?", a: "Aconcagua", p: 300 },
            { q: "Quale nazione al mondo possiede in assoluto il maggior numero di fusi orari (inclusi i territori d'oltremare)?", a: "Francia (12 fusi)", p: 300 },
            { q: "Qual è l'isola più grande del mondo (se si esclude il continente australiano)?", a: "Groenlandia", p: 300 },
            { q: "Quale vasto deserto freddo asiatico si estende a cavallo tra il nord della Cina e il sud della Mongolia?", a: "Deserto del Gobi", p: 300 },
            { q: "Con i suoi 8.848 metri, qual è la montagna più alta della Terra sul livello del mare?", a: "Monte Everest", p: 300 },
            { q: "Qual è la capitale della gelida nazione insulare dell'Islanda?", a: "Reykjavík", p: 300 },
            { q: "Qual è il più piccolo stato sovrano del mondo per estensione territoriale?", a: "Città del Vaticano", p: 300 },
            { q: "Quale possente fiume africano attraversa due volte l'equatore nel suo bacino pluviale?", a: "Fiume Congo", p: 300 },
            { q: "Quale lago salato, situato tra Israele e Giordania, rappresenta il punto più basso della terraferma?", a: "Mar Morto", p: 300 },
            { q: "Quale grande fiume europeo attraversa ben 10 nazioni prima di sfociare nel Mar Nero?", a: "Danubio", p: 300 },
            // 400
            { q: "Il Sudafrica possiede tre capitali. Quale di esse ospita il potere esecutivo ed amministrativo?", a: "Pretoria", p: 400 },
            { q: "Come si chiama il punto più profondo conosciuto degli oceani, situato nella Fossa delle Marianne?", a: "Abisso Challenger (Challenger Deep)", p: 400 },
            { q: "A quale nazione appartiene l'exclave europea di Kaliningrad, incastonata tra Polonia e Lituania?", a: "Russia", p: 400 },
            { q: "Come si chiama l'attuale capitale del Kazakistan, nota anche brevemente come Nur-Sultan in passato?", a: "Astana", p: 400 },
            { q: "Qual è la capitale remota e fredda della Mongolia?", a: "Ulan Bator", p: 400 },
            { q: "Quale vasto specchio d'acqua salata, chiuso tra Europa ed Asia, detiene il record di più grande lago al mondo?", a: "Mar Caspio", p: 400 },
            { q: "Quale fondamentale e stretto passaggio marittimo collega il Golfo Persico col Golfo di Oman?", a: "Stretto di Hormuz", p: 400 },
            { q: "Quale stretto in Turchia divide fisicamente la città di Istanbul tra il lato europeo e quello asiatico?", a: "Stretto del Bosforo", p: 400 },
            { q: "Quale deserto cileno è noto per essere il luogo non polare più arido della Terra?", a: "Deserto di Atacama", p: 400 },
            { q: "Quale montagna al confine tra Italia e Francia è considerata il 'Tetto d'Europa' coi suoi 4.810m?", a: "Monte Bianco", p: 400 },
            // 500
            { q: "Quale minuscola nazione insulare dell'Oceania detiene la particolarità di non avere una vera capitale ufficiale?", a: "Nauru", p: 500 },
            { q: "Quale trafficatissimo stretto marittimo asiatico separa la penisola malese dall'isola indonesiana di Sumatra?", a: "Stretto di Malacca", p: 500 },
            { q: "A quale nazione sudamericana appartiene formalmente la remota Isola di Pasqua (Rapa Nui)?", a: "Cile", p: 500 },
            { q: "Il monte Lhotse, parte del massiccio dell'Everest, è quale vetta al mondo in ordine di altezza?", a: "La quarta montagna più alta del mondo", p: 500 },
            { q: "Quale nazione insulare nel Pacifico è l'unica ad avere territori in tutti e quattro gli emisferi terrestri?", a: "Kiribati", p: 500 },
            { q: "Qual è la capitale del Suriname, nazione situata sulla costa settentrionale del Sud America?", a: "Paramaribo", p: 500 },
            { q: "Quale pericoloso e ventoso stretto marino, scoperto nel 1520, separa l'estremità sud del Sud America dalla Terra del Fuoco?", a: "Stretto di Magellano", p: 500 },
            { q: "Quale antico lago siberiano, riserva immensa d'acqua dolce, è il lago più profondo della Terra?", a: "Lago Bajkal", p: 500 },
            { q: "In quale stato africano si trova il maestoso vulcano del Kilimangiaro?", a: "Tanzania", p: 500 },
            { q: "Quale impronunciabile città è l'arida capitale dello stato africano del Burkina Faso?", a: "Ouagadougou", p: 500 }
        ]
    },
    {
        id: "games",
        title: "Videogiochi",
        questions: [
            // 100
            { q: "Quale iconica azienda giapponese è la creatrice di Super Mario e Zelda?", a: "Nintendo", p: 100 },
            { q: "Qual è il gioco dei blocchi cadenti creato nel 1984 da Aleksej Pažitnov?", a: "Tetris", p: 100 },
            { q: "Come si chiama il velocissimo porcospino blu mascotte di casa SEGA?", a: "Sonic the Hedgehog", p: 100 },
            { q: "In quale celebre gioco arcade della Namco controlliamo una sfera gialla mangia-palline in un labirinto?", a: "Pac-Man", p: 100 },
            { q: "Qual è il videogioco più venduto in assoluto della storia, incentrato sui blocchi cubici e il crafting?", a: "Minecraft", p: 100 },
            { q: "Qual è il nome della Principessa ricorrente del Regno di Hyrule, da salvare in The Legend of Zelda?", a: "Principessa Zelda", p: 100 },
            { q: "Quale innovativa console di Nintendo del 2006 ha introdotto i sensori di movimento e gli avatar Mii?", a: "Nintendo Wii", p: 100 },
            { q: "Qual è il nome dell'idraulico vestito di verde, fifone e fratello di Mario?", a: "Luigi", p: 100 },
            { q: "In quale diffusissimo gioco Battle Royale della Epic Games si usa la valuta in-game 'V-Bucks'?", a: "Fortnite", p: 100 },
            { q: "Quale colosso dell'elettronica produce la popolarissima linea di console PlayStation?", a: "Sony", p: 100 },
            // 200
            { q: "Quale piccola software house svedese ha originariamente sviluppato Minecraft?", a: "Mojang", p: 200 },
            { q: "Qual è il vero nome del silenzioso eroe vestito di verde in The Legend of Zelda?", a: "Link", p: 200 },
            { q: "Come si chiama il supersoldato Spartan-117, protagonista della saga fantascientifica Halo?", a: "Master Chief", p: 200 },
            { q: "In quale anno è stata lanciata la primissima console PlayStation in Giappone?", a: "1994", p: 200 },
            { q: "Come si chiama l'archeologa britannica e agile avventuriera protagonista di Tomb Raider?", a: "Lara Croft", p: 200 },
            { q: "Quale iconico e amatissimo Pokémon di tipo Elettro ricopre il numero #025 nel Pokédex Nazionale?", a: "Pikachu", p: 200 },
            { q: "Come si chiama la distopica città sottomarina in stile Art déco del primo BioShock?", a: "Rapture", p: 200 },
            { q: "Quale diffusissimo brand di simulazione calcistica è stato prodotto da EA Sports prima di cambiare nome nel 2023?", a: "FIFA", p: 200 },
            { q: "In quale celebre MOBA l'azione principale si svolge nell'arena 'Landa degli Evocatori' (Summoner's Rift)?", a: "League of Legends", p: 200 },
            { q: "In quale anno debuttò GTA III, inaugurando l'era in 3D dei giochi open-world di Rockstar?", a: "2001", p: 200 },
            // 300
            { q: "Di quale cruenta e spettacolare saga d'azione è protagonista lo Spartano Kratos?", a: "God of War", p: 300 },
            { q: "In quale nazione asiatica ha avuto inizio nel 1996 il successo senza precedenti dei videogiochi Pokémon (Rosso e Verde)?", a: "Giappone", p: 300 },
            { q: "Qual è il nome proprio del cinico cacciatore di mostri mutato protagonista di The Witcher?", a: "Geralt di Rivia", p: 300 },
            { q: "Qual è il nome in codice del supersoldato specialista di infiltrazione protagonista di Metal Gear Solid?", a: "Solid Snake", p: 300 },
            { q: "Quale stimata software house giapponese ha sviluppato titoli punitivi come Dark Souls, Bloodborne e Elden Ring?", a: "FromSoftware", p: 300 },
            { q: "Come si chiama la Principessa del Regno dei Funghi, costantemente rapita da Bowser?", a: "Principessa Peach", p: 300 },
            { q: "Quale pericoloso mostro verde esplosivo, nato da un bug grafico, infesta i mondi di Minecraft?", a: "Creeper", p: 300 },
            { q: "Come si chiama la caotica, tecnologica e violenta megalopoli in cui è ambientato Cyberpunk 2077?", a: "Night City", p: 300 },
            { q: "Quale celebre e longevo GdR fantasy di Bethesda ha come capitoli Morrowind, Oblivion e Skyrim?", a: "The Elder Scrolls", p: 300 },
            { q: "In The Last of Us, i mostri infetti che minacciano la sopravvivenza dei protagonisti sono vittime di quale fungo parassita?", a: "Cordyceps", p: 300 },
            // 400
            { q: "Quale celebre e visionario game designer giapponese è la mente creativa dietro la serie Metal Gear?", a: "Hideo Kojima", p: 400 },
            { q: "In quale anno fu lanciata sul mercato nordamericano la primissima console e 'scatola nera' Xbox di Microsoft?", a: "2001", p: 400 },
            { q: "Qual è la console portatile col design a doppio schermo più venduta di tutti i tempi, rilasciata da Nintendo nel 2004?", a: "Nintendo DS", p: 400 },
            { q: "Quale pionieristica software house texana ha gettato le basi degli FPS creando Wolfenstein 3D e Doom (1993)?", a: "id Software", p: 400 },
            { q: "Come si chiama il versatile e popolarissimo motore grafico sviluppato e licenziato da Epic Games?", a: "Unreal Engine", p: 400 },
            { q: "Qual è l'anno della cosiddetta 'Grande Crisi dei Videogiochi' che colpì l'industria nordamericana a causa della saturazione del mercato?", a: "1983", p: 400 },
            { q: "Quale geniale programmatore di id Software ha scritto motori grafici rivoluzionari in 3D per Doom e Quake?", a: "John Carmack", p: 400 },
            { q: "Qual è il vero nome del programmatore svedese noto con lo pseudonimo di 'Notch', creatore di Minecraft?", a: "Markus Persson", p: 400 },
            { q: "Quale eccentrico game designer britannico creò god games come Populous e Black & White?", a: "Peter Molyneux", p: 400 },
            { q: "In Final Fantasy VII (1997), come si chiama il letale antagonista dai lunghi capelli argentati e la grande katana?", a: "Sephiroth", p: 400 },
            // 500
            { q: "Quale pionieristica azienda di videogiochi produsse il cabinato commerciale di Pong nel 1972?", a: "Atari", p: 500 },
            { q: "Chi è il leggendario game designer della Nintendo, padre di Mario, Donkey Kong, Pikmin e Zelda?", a: "Shigeru Miyamoto", p: 500 },
            { q: "Quale acclamata azienda di Seattle, guidata da Gabe Newell, ha creato il capolavoro Half-Life nel 1998?", a: "Valve Corporation", p: 500 },
            { q: "Quale colossale gioco per Nintendo 64 del 1998 detiene stabilmente il punteggio più alto in assoluto sul sito Metacritic?", a: "The Legend of Zelda: Ocarina of Time", p: 500 },
            { q: "Come era battezzato il progetto di console con lettore CD nato dalla partnership (poi fallita) tra Nintendo e Sony?", a: "Nintendo PlayStation (o SNES-CD)", p: 500 },
            { q: "Come si chiama il sofisticato motore fisico middleware utilizzato dal Source Engine e in centinaia di altri giochi 3D?", a: "Havok", p: 500 },
            { q: "Quale programmatore di giochi di ruolo per PC, noto anche come 'Lord British', creò la serie di RPG Ultima?", a: "Richard Garriott", p: 500 },
            { q: "Creato nel 1971 da Nolan Bushnell, quale è considerato il primo videogioco arcade commerciale in assoluto?", a: "Computer Space", p: 500 },
            { q: "Qual è l'esatta combinazione dei famosi dieci tasti del trucco segreto noto come 'Konami Code'?", a: "Su Su Giù Giù Sinistra Destra Sinistra Destra B A", p: 500 },
            { q: "In quale fatidico anno venne rilasciato il disastroso gioco 'E.T. the Extra-Terrestrial' per Atari 2600?", a: "1982", p: 500 }
        ]
    },
    {
        id: "art",
        title: "Arte",
        questions: [
            // 100
            { q: "Quale genio rinascimentale è l'autore del dipinto 'La Gioconda' (o Monna Lisa)?", a: "Leonardo da Vinci", p: 100 },
            { q: "Quale celebre pittore spagnolo ha dipinto la grande e drammatica tela di denuncia 'Guernica'?", a: "Pablo Picasso", p: 100 },
            { q: "Quale grande artista italiano ha affrescato la gigantesca volta della Cappella Sistina in Vaticano?", a: "Michelangelo Buonarroti", p: 100 },
            { q: "In quale capitale europea si trova l'enorme e prestigioso Museo del Louvre?", a: "Parigi", p: 100 },
            { q: "Quale celebre scultura di Michelangelo si trova all'Accademia di Firenze e rappresenta l'eroe biblico che sconfisse Golia?", a: "David", p: 100 },
            { q: "Quale artista norvegese ha dipinto il celebre quadro d'angoscia intitolato 'L'urlo'?", a: "Edvard Munch", p: 100 },
            { q: "Quale tormentato pittore post-impressionista si tagliò parte dell'orecchio sinistro?", a: "Vincent van Gogh", p: 100 },
            { q: "In quale città italiana si trova il maestoso Anfiteatro Flavio, universalmente noto come Colosseo?", a: "Roma", p: 100 },
            { q: "Quale corrente artistica, resa celebre da Seurat, dipingeva i quadri accostando piccoli punti di colore puro?", a: "Puntinismo (o Pointillisme)", p: 100 },
            { q: "Come è chiamato il cupo e malinconico periodo artistico di Picasso che ha preceduto il più sereno 'Periodo Rosa'?", a: "Periodo Blu", p: 100 },
            // 200
            { q: "Quale grande maestro fiorentino ha dipinto il celebre quadro allegorico 'La Nascita di Venere'?", a: "Sandro Botticelli", p: 200 },
            { q: "Quale pittore olandese dipinse i vorticosi e vibranti cieli della 'Notte stellata'?", a: "Vincent van Gogh", p: 200 },
            { q: "In quale città italiana si trova l'importantissimo e ricchissimo museo statale della Galleria degli Uffizi?", a: "Firenze", p: 200 },
            { q: "Quale artista americano è considerato il re della Pop Art e ha riprodotto in serie le lattine di zuppa Campbell?", a: "Andy Warhol", p: 200 },
            { q: "Chi è l'autore del grandioso e discusso affresco 'L'Ultima Cena' situato a Milano?", a: "Leonardo da Vinci", p: 200 },
            { q: "Quale geniale pittore surrealista spagnolo è famoso per gli orologi molli del quadro 'La persistenza della memoria'?", a: "Salvador Dalí", p: 200 },
            { q: "Quale stile architettonico medievale è caratterizzato dallo slancio verticale, dagli archi a sesto acuto e dalle ampie vetrate colorate?", a: "Gotico", p: 200 },
            { q: "Quale grande scultore francese ottocentesco modellò la celebre statua de 'Il pensatore'?", a: "Auguste Rodin", p: 200 },
            { q: "Quale celebre e sofferente pittrice messicana è famosa per i suoi abiti floreali e gli innumerevoli e introspettivi autoritratti?", a: "Frida Kahlo", p: 200 },
            { q: "In quale capitale europea è possibile visitare il vasto museo del Prado?", a: "Madrid", p: 200 },
            // 300
            { q: "Quale insigne scultore ed architetto fu il massimo esponente del Barocco romano e progettò il Colonnato di San Pietro?", a: "Gian Lorenzo Bernini", p: 300 },
            { q: "Quale espressionista norvegese ha realizzato la disturbante pittura su cartone 'L'Urlo' nel 1893?", a: "Edvard Munch", p: 300 },
            { q: "Quale virtuoso scultore neoclassico veneto ha scolpito la dolce e perfetta opera in marmo 'Amore e Psiche'?", a: "Antonio Canova", p: 300 },
            { q: "Quale pittore francese espose 'Impressione, levar del sole', il quadro che finì per dare involontariamente il nome all'Impressionismo?", a: "Claude Monet", p: 300 },
            { q: "Quale enigmatico pittore olandese seicentesco ha dipinto la luminosa tela 'Ragazza col turbante' (o 'La ragazza con l'orecchino di perla')?", a: "Jan Vermeer", p: 300 },
            { q: "Qual è lo pseudonimo del celebre e provocatorio artista di strada (street artist) britannico la cui vera identità è ignota?", a: "Banksy", p: 300 },
            { q: "Quale fondatore della Secessione viennese realizzò 'Il bacio' decorandolo con lamine di vera foglia d'oro?", a: "Gustav Klimt", p: 300 },
            { q: "Chi ha affrescato la grandiosa 'Scuola di Atene' all'interno della Stanza della Segnatura in Vaticano?", a: "Raffaello Sanzio", p: 300 },
            { q: "Quale pittore francese post-impressionista fuggì in Polinesia per dipingere le sue celebri e variopinte scene di vita tahitiana?", a: "Paul Gauguin", p: 300 },
            { q: "In quale effervescente secolo ebbe origine in Italia, e specificamente a Firenze, l'epoca del Rinascimento?", a: "XV Secolo (1400)", p: 300 },
            // 400
            { q: "Quale rivoluzionario pittore fiammingo è noto per l'iperdettagliato 'Ritratto dei coniugi Arnolfini' dipinto ad olio?", a: "Jan van Eyck", p: 400 },
            { q: "Quale colto architetto rinascimentale veneto teorizzò la proporzione e progettò 'La Rotonda' (Villa Almerico Capra)?", a: "Andrea Palladio", p: 400 },
            { q: "Quale visionario architetto statunitense, fautore dell'architettura organica, progettò la forma a spirale del Museo Guggenheim di New York?", a: "Frank Lloyd Wright", p: 400 },
            { q: "Quale maestro pittore della corte spagnola, abilissimo nella prospettiva atmosferica, realizzò il capolavoro 'Las Meninas'?", a: "Diego Velázquez", p: 400 },
            { q: "Quale pittore romantico tedesco realizzò la sublime e malinconica tela 'Viandante sul mare di nebbia'?", a: "Caspar David Friedrich", p: 400 },
            { q: "In quale anno il dadaista Marcel Duchamp presentò in mostra un orinatoio rovesciato, intitolandolo 'Fontana' e scioccando la critica?", a: "1917", p: 400 },
            { q: "Quale pittore russo, autore della teoria 'Lo spirituale nell'arte', è considerato il fondatore dell'astrattismo moderno col suo 'Primo acquerello astratto'?", a: "Vasilij Kandinskij", p: 400 },
            { q: "Chi è l'eccentrico e geniale architetto catalano che progettò e lavorò tutta la vita all'immensa Basilica della Sagrada Família a Barcellona?", a: "Antoni Gaudí", p: 400 },
            { q: "Quale assoluto pioniere della pittura rinascimentale italiana rivoluzionò l'arte gotica affrescando nel Trecento la Cappella degli Scrovegni a Padova?", a: "Giotto di Bondone", p: 400 },
            { q: "Quale singolare artista olandese del primo Cinquecento è l'autore del trittico bizzarro, infernale e allucinante 'Trittico del Giardino delle delizie'?", a: "Hieronymus Bosch", p: 400 },
            // 500
            { q: "Quale magistrale scultore napoletano riuscì nel 1753 a scolpire l'incredibile panneggio marmoreo del 'Cristo velato'?", a: "Giuseppe Sanmartino", p: 500 },
            { q: "Quale inventivo architetto progettò l'immensa cupola autoportante in muratura della Cattedrale di Santa Maria del Fiore a Firenze?", a: "Filippo Brunelleschi", p: 500 },
            { q: "Quale audace architetto contemporaneo canadese ha disegnato le forme destrutturate, curve e rivestite in titanio del Museo Guggenheim di Bilbao?", a: "Frank Gehry", p: 500 },
            { q: "Quale geniale ma turbolento pittore italiano rivoluzionò la pittura seicentesca usando i violenti contrasti di chiaroscuro ne 'La vocazione di San Matteo'?", a: "Caravaggio (Michelangelo Merisi)", p: 500 },
            { q: "Come si chiama il celebre e drammatico gruppo scultoreo ellenistico, ritrovato a Roma nel 1506, che rappresenta un sacerdote troiano e i suoi figli stritolati da serpenti marini?", a: "Gruppo del Laocoonte", p: 500 },
            { q: "Quale caparbia pittrice italiana del periodo barocco, seguace del caravaggismo, dipinse la violenta e celebre scena di 'Giuditta che decapita Oloferne'?", a: "Artemisia Gentileschi", p: 500 },
            { q: "Quale scultore e bronzista greco classico teorizzò, col suo 'Doriforo', il canone della perfetta proporzione del corpo umano?", a: "Policleto", p: 500 },
            { q: "Quale aggressivo movimento artistico d'avanguardia italiano, che esaltava la velocità e la macchina, fu fondato da Filippo Tommaso Marinetti nel 1909?", a: "Futurismo", p: 500 },
            { q: "Chi è il rivoluzionario architetto di origine svizzera che teorizzò i cinque punti della nuova architettura e progettò 'Villa Savoye'?", a: "Le Corbusier (Charles-Édouard Jeanneret-Gris)", p: 500 },
            { q: "Quale faraone egizio della IV dinastia commissionò la costruzione della più grande ed imponente piramide della necropoli di Giza?", a: "Cheope (Khufu)", p: 500 }
        ]
    }
    {
        id: "myth_greek",
        title: "Mitologia Greca",
        questions: [
            // 100
            { q: "Quale dio è il re dell'Olimpo e signore del cielo e dei fulmini?", a: "Zeus", p: 100 },
            { q: "Quale divinità impugna il tridente ed è considerato il dio del mare e dei terremoti?", a: "Poseidone", p: 100 },
            { q: "Quale dea greca, nata dalla testa di Zeus, è la protettrice della saggezza, delle arti e della guerra giusta?", a: "Atena", p: 100 },
            { q: "Quale astuto re di Itaca è il protagonista dell'epico viaggio narrato nell'Odissea?", a: "Ulisse (Odisseo)", p: 100 },
            { q: "Quale mitico eroe ateniese riuscì ad addentrarsi nel Labirinto di Creta e a uccidere il Minotauro?", a: "Teseo", p: 100 },
            { q: "Quale invincibile guerriero greco, eroe dell'Iliade, aveva il proprio unico punto debole nel tallone?", a: "Achille", p: 100 },
            { q: "Quale dio greco è il sovrano incontrastato del regno dei morti e del mondo sotterraneo?", a: "Ade", p: 100 },
            { q: "Come si chiama il leggendario cavallo alato bianco nato dal sangue di Medusa?", a: "Pegaso", p: 100 },
            { q: "Quale dea olimpica del matrimonio e della fedeltà coniugale è la moglie (e sorella) di Zeus?", a: "Era", p: 100 },
            { q: "Quale dio greco, dotato di calzari alati, svolge il ruolo di messaggero degli dei e protettore dei viaggiatori?", a: "Ermes", p: 100 },
            // 200
            { q: "Quale delle tre Gorgoni era l'unica mortale e aveva serpenti velenosi al posto dei capelli?", a: "Medusa", p: 200 },
            { q: "Come si chiama il traghettatore che trasporta le anime dei morti attraverso il fiume infernale Acheronte?", a: "Caronte", p: 200 },
            { q: "Quale dio olimpico è la violenta e sanguinaria personificazione della guerra?", a: "Ares", p: 200 },
            { q: "Nata dalla spuma del mare a Cipro, quale dea greca incarna l'amore e la bellezza?", a: "Afrodite", p: 200 },
            { q: "Quale invincibile eroe greco affrontò e strangolò il temibile Leone di Nemea nella sua prima fatica?", a: "Eracle (Ercole)", p: 200 },
            { q: "Qual è il nome del possente ciclope, figlio di Poseidone, che venne accecato da Ulisse e dai suoi compagni?", a: "Polifemo", p: 200 },
            { q: "Quale Titano rubò il fuoco agli dei per donarlo all'umanità, finendo incatenato a una roccia del Caucaso?", a: "Prometeo", p: 200 },
            { q: "Quale giovane precipitò in mare perché volò troppo vicino al sole, facendo sciogliere le sue ali di cera?", a: "Icaro", p: 200 },
            { q: "Quale dio olimpico, gemello di Artemide, è il signore della luce, delle arti, della musica e della divinazione?", a: "Apollo", p: 200 },
            { q: "Quale fu la prima donna mortale, famosa per aver aperto per curiosità il vaso che conteneva tutti i mali del mondo?", a: "Pandora", p: 200 },
            // 300
            { q: "Quale dea olimpica è la protettrice dell'agricoltura, delle messi e delle stagioni?", a: "Demetra", p: 300 },
            { q: "Come si chiama il mostruoso cane a tre teste che fa la guardia all'ingresso degli Inferi impedendo l'uscita ai morti?", a: "Cerbero", p: 300 },
            { q: "Quale potente maga trasformò i compagni di Ulisse in maiali sull'isola di Eea?", a: "Circe", p: 300 },
            { q: "Quale abile tessitrice mortale fu trasformata in un ragno per aver osato sfidare la dea Atena?", a: "Aracne", p: 300 },
            { q: "Quale dio dell'Olimpo è associato al vino, all'estasi, all'ebbrezza e al teatro?", a: "Dioniso", p: 300 },
            { q: "Quale Titano fu condannato da Zeus a reggere per l'eternità la volta celeste sulle proprie spalle?", a: "Atlante", p: 300 },
            { q: "Quale dio olimpico, zoppo ma eccezionale fabbro e signore del fuoco, era il marito di Afrodite?", a: "Efesto", p: 300 },
            { q: "Quale gigantesco cacciatore fu ucciso dalla puntura di uno scorpione e successivamente trasformato in una costellazione?", a: "Orione", p: 300 },
            { q: "Qual è il nome della ninfa del mare (Nereide) che fu madre dell'eroe Achille e cercò di renderlo immortale?", a: "Teti", p: 300 },
            { q: "Quale eroe della Tessaglia guidò l'equipaggio degli Argonauti alla ricerca del prezioso Vello d'Oro?", a: "Giasone", p: 300 },
            // 400
            { q: "Quale eroico principe di Corinto uccise il mostro sputafuoco Chimera cavalcando il destriero Pegaso?", a: "Bellerofonte", p: 400 },
            { q: "Quale re fu condannato negli Inferi a spingere eternamente un pesante masso sulla cima di un monte, per poi vederlo rotolare giù?", a: "Sisifo", p: 400 },
            { q: "Quale re fu punito nel Tartaro con una fame e una sete inestinguibili pur essendo immerso in un lago e circondato da frutti?", a: "Tantalo", p: 400 },
            { q: "Quale eroe greco, figlio di Zeus e Danae, riuscì a decapitare la Gorgone Medusa usando uno scudo riflettente?", a: "Perseo", p: 400 },
            { q: "Qual è il nome della dea greca del focolare domestico, primogenita di Crono e Rea, nota per la sua natura pacifica?", a: "Estia", p: 400 },
            { q: "Qual è il nome del celebre indovino cieco della città di Tebe, il cui spirito viene evocato da Ulisse nell'Ade?", a: "Tiresia", p: 400 },
            { q: "Quale velocissima cacciatrice fu sconfitta in una gara di corsa da Ippomene, che la distrasse lanciando tre mele d'oro?", a: "Atalanta", p: 400 },
            { q: "Su quale fiume infernale, le cui acque rendevano invulnerabili, gli dei prestavano i loro giuramenti più solenni e irrevocabili?", a: "Stige", p: 400 },
            { q: "Qual è il nome della figlia di Demetra, rapita da Ade mentre coglieva fiori per diventare la regina degli Inferi?", a: "Persefone (o Core)", p: 400 },
            { q: "Quale terribile mostro marino a sei teste dimorava in una caverna dello stretto di Messina, opposto al gorgo Cariddi?", a: "Scilla", p: 400 },
            // 500
            { q: "Quale re di Micene impose e supervisionò le celebri dodici fatiche affrontate da Eracle come espiazione?", a: "Euristeo", p: 500 },
            { q: "Come si chiamano le tre Moire, implacabili divinità che tessono, misurano e recidono il filo del destino umano?", a: "Cloto, Lachesi e Atropo", p: 500 },
            { q: "Quale mostruoso drago-serpente dalle cento teste, figlio di Tifone, faceva la guardia all'albero dei pomi d'oro delle Esperidi?", a: "Ladone", p: 500 },
            { q: "Quale titano, fratello di Prometeo, sposò Pandora e ha un nome che significa letteralmente 'colui che pensa dopo'?", a: "Epimeteo", p: 500 },
            { q: "Qual è il nome della ninfa che implorò di essere tramutata in una pianta di alloro per sfuggire all'amore non corrisposto di Apollo?", a: "Dafne", p: 500 },
            { q: "Come si chiamava il colossale gigante di bronzo che proteggeva le coste dell'isola di Creta, infine sconfitto dagli Argonauti e da Medea?", a: "Talo (o Talos)", p: 500 },
            { q: "Quale impavido eroe greco, re di Argo, arrivò a ferire in combattimento persino gli dei Ares e Afrodite durante la guerra di Troia?", a: "Diomede", p: 500 },
            { q: "Come si chiama la Musa greca che presiede e protegge la disciplina della storia, spesso raffigurata con una pergamena in mano?", a: "Clio", p: 500 },
            { q: "Quale potente divinità primordiale personifica la Notte ed è temuta persino da Zeus, essendo madre di Ipno e Tanato?", a: "Notte (Nyx)", p: 500 },
            { q: "Chi era il tragico eroe tebano che, per sfuggire a una profezia, finì per uccidere inconsapevolmente il padre Laio e sposare la madre Giocasta?", a: "Edipo", p: 500 }
        ]
    }
];
